### ISSUE TITLE
Evaporation losses are missing fermentation and kettle dead space

### ISSUE THREAD

**Issue by kschluns** [BenjaminBearce/BK_Brew#14]
Currently, only the batch size is being used to calculate evaporation losses.

The procedure for brewing, as I know it, is as follows. I'm ignoring shrinkage for sake of simplicity.

(1) measure out mash and sparge volume with cold water
(2) go through mashing process which includes loss of volume from mash dead space,  grain absorption, and lauter tun dead space
(3) then boil for however long 
(5) siphon from kettle, which leaves behind kettle dead space 
(6) ferment, which leaves behind fermentation dead space

To get total water, you would work backwards from these steps, starting with your final batch size and doing the opposite of each step. Here is an example.

Final Batch Size = 5 gal
(6) TV += fermDead
(5) TV += kettleDead
(4) TV /= evapFactor
...
..
and so on. In the current software, step 4 occurs before steps 5 and 6. 

I think my main point is that the pre-boil volume in the current software is too low. It does not consider the extra volume that will be there from the dead spaces. 

I can see how this can be confusing because why are we excluding the mash and lauter dead space volumes and grain absorption volume in the pre-boil volume? 

The reason is because these volumes have already been removed from the total volume at the moment that the boil starts.

Proposed formula:

```
    EvL <- reactive({
            (BS()+kettleLoss()+fermentationLoss())*((input$boilTime/60)*(input$evap/100)/(1-(input$boilTime/60)*(input$evap/100)))
    })
```

Current formula: 

```
    EvL <- reactive({
            BS()*((input$boilTime/60)*(input$evap/100)/(1-(input$boilTime/60)*(input$evap/100)))
    })
```

**Comment by BenjaminBearce** [comment]
Dude bro..execellent!!! 4 befo 5 and 6, totalllllllyyyyy...I'm having a beer and doing this...So cool.

**Comment by BenjaminBearce** [comment]
It's in there brah! Check it out brah! Close me brah, close me!

**Comment by kschluns** [comment]
PASSED QA!
