### ISSUE TITLE
INVESTIGATE - Should fermentables equation only use batch size volume to calculate lbs. grain needed?

### ISSUE THREAD

**Issue by kschluns** [BenjaminBearce/BK_Brew#16]
This isn't a bug as much as it is a question that I think we should clarify and answer.

Let's say we want to make a beer with OG = 1.050 and we are shooting for final volume of 5 gallons.

From Daniels, we always learned to just take that final volume and multiply by OG to get total OG, which then gets used to calculate pounds of each grain. 

However, I'm wondering whether total OG should actually be calculated from post-boil volume and not final batch size. Between post-boil volume and final batch, there is both kettle dead space and fermentation dead space. 

If we go down this route, it would change the fermentables formula from:

```
            ...
            ....
            totalGravity <- OG*input$batchSize #OG*Gal
            ....
            ...
```

to:

```
            ...
            ....
            totalGravity <- OG*(input$batchSize+input$fermentationTankLoss+input$KettleDeadSpace) #OG*Gal
            ....
            ...
```

This probably explains why we have never been able to get above 70% efficiency, because we are always underestimating the true amount of grain we need.

**Comment by kschluns** [comment]
The reason I found this is because if you do the following:

batchSize = 5.5 gallons
fermDead = 0.0 gallons

it will produce different pounds of grain than

batchSize = 5.0 gallons
fermDead = 0.5 gallons

...and I thought this was strange. Turns out that it comes back to this!

**Comment by BenjaminBearce** [comment]
Can you guess what brah...fixed.

**Comment by kschluns** [comment]
PASSED QA!
